@Restaurants.API_HostAddress = https://localhost:7226
@Host = https://localhost
@Port = 7226

@AdminAccesToken = CfDJ8FUx_czOlwhOr4yFD0keTAzmlaKZo5hvH-M4RD7wMLs7q1CHt0CV9YIXqOw3CeY6BagZYpUPJSfQSS-3mUr8DnPS_h52CL5aDkU-1RUpAUobEzwifoWxZzUBW3ONIvPX2MKIh-Fe07-BNrzXRQCTjbHmc2uG11Y5F9KL4EEfAZUQAPaM-qzqG7RIJGCYKCzTEYZ6iIGeVvUWnjr2NNx2I1ObgMt622eovVEXm8cqwPCbp9kjy7yVib_GbARDo50kj4y7zGQ6ZyMsAm2xfc-1nuKCFwH1n007i71DCnvp_XbN3bMc9-EMqI8wO-tJYeh0z_3RQkuukFv-H8GW9Jc0DqRXw6xBAI507ImvEEq2PCXCwImqWMjGc_oxPkitByVgZXjEYCdyBhpejqBQGFEmVZnDhJ4-yDqyIv44NHt-hrvU5y-h7z8-Q8iAtcsoG8a2S7V2TI3FxD0gWylqwT-WsEMgZgxhCWDhoQ4M0yOdoyLXLzDu0y0aY-0j_Whk3vJLQnrSeDFQGNx_W_ZthnwCIqWTb3JpWIss2yxUmYH3yXHpsW9OIb-d3f-Z-_mD7W9-6EcDlp_2jnlMG7e7SZKnUWSXCsRbJchi0kAZUQl-UxF81c9cuEku6K-_dLRyPJ1RVLItXvEVCz5UE7rQjAL6mL6MuzzoR-mJPaE_C3VZcM0fZ4yydkTzhV8a3aS6vJDn3Z6SXgfwSUtRJoOzkPlhZgw
@SimpleAccesToken = CfDJ8FUx_czOlwhOr4yFD0keTAz7mNgsOHV9tlpebAHM7ivkAvdO-T1yT9V1IdkLZgo__EeZayiZQelyvIpm2UkLm0SPiKJhmOM1LAyEIllrca2DhlEE-RqNWiSZvObw-ESW_0VaWs33U_A4xkPe3xNF65LrqIPPXQJqu1LkxF7XR4hsHx4dc8BsF4n1oz29j_pbIsVp9w03zgPMvDX3NCx-7scga-xiB_NORLfeKUneF7Z07KJM6Jz6L_D5YSPROH07KLTn4aZa2SsjhCXk1xMO9bxkQFbYPB0y1oA_3dTw1QmJJr4Y6dYzMHHjeCYM9n55t7H28YGT46bVrBkKgQIhQpV699UF1y48rAS5VI83ECvXJcy5Fwr92MhbabOTBJvvIPJ152-bXxBnzvkjUpiVzcEfoJxdQeE5VB-Pk9CZKpahxsSXn-xCFwgOQ0mq97BZOqgccOKqUD71Ew_vUQas_L2yzCr3lIaof1gI-8ESiRZP_IuReaRCIJh30T9Dg2aBpzDxeWtuf0ozToKO6cRTCaEsTrqJb2dnWJea1P1wDE42_sNB2sPFPKpsUod0Qxks7g1-ogkAXi7zMZljPiykgptzJDDyqPROBHrvruqZSJ0bL0meWqXO-ys_Gk46012qd5pnBjbg0bjCpo4LyNp4s68zdHaG6zNl6g2tdYilVivQaRA_Uz3G8aeGgyLb5RVjdGbzPVuDd26p-ujUnjJOBJY
@OwnerAccesToken = CfDJ8FUx_czOlwhOr4yFD0keTAxj_RC6wsWqEdnm5YwKVoyJdu6lZGeY2kV1Cm4SnIvV1VBAFxD8A0odf3u-lzKUF6_RlBlWvJTDwIWfNUz8H2ccU9xFt6CpYdWt-mvOroWs0kFHAHMVzZJLL7dDxaQKAVDARb3XJ4SD8g7JtDxPoGZdJaCasz5TCHzcr6WkFyPCnSMgwbL_9hR8nCKGEQDubWxyTzVF6tdoN586_DMbIeiFC_Jzsc35N4OijhF5VgqpwjeokKsVNfQHpTlRkEGRZDNHdi1gwssK9Iesfve56qsg2iwZ3gdJheXXQf7TN60RaF0WGrzuEJjulwnYPYBOvTlzGK-mToOK9cT9K6_Bfjm29Z31voOgLcLk6DbdY6xkX824llMgIzTLJ9T-yqZLWA502fOM9nvm5xlo8iPMujdeZRo2_8LQoC7Gc85W2mJ1i-NCTf5lvqFIX64XJV8vF7Cpmh7KlNSD8EwLqge3kgS4TZnXDGEoqbJH8QySaROF18UwawUIEVwHbKLVLwbhJ_6LOXbc7keyKDD3BRGY1f6TQ2AVt-OMZ_xSUMQahVzeg5u7M3Rekq3ai1vdPNg06uwnyMGwDGgfOWi5KpZqlAYq7_8a6LxmgbqrkgZTSOa4tdbELl2PcmxLRbUmVj3HAggM0XEzHZGL2OeEQBeM1k8-tP3FsNbnS5QkyHitD78_CE4OJ-zCHAefY_Q0gA6GGWc3KgdEVnyET_RYSvn54LUzrC323l1JOZonoNlzDt0EZc6s2I5DjmRGYAj9HqcyqyT60-Ue66Pfnc71G8dudMeaS4M6lyPSZ5wlDqj63RWwpA

@RestaurantsAPI_HostAddress = {{Host}}:{{Port}}


GET {{RestaurantsAPI_HostAddress}}/api/restaurants?PageSize=20&PageNumber=5

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants?SearchPhrase=wiza&PageSize=20&PageNumber=1
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/8A221E03-F2A4-44E9-5C17-08DCD803C421
Authorization : Bearer {{AccesToken}}
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/8A221E03-F2A4-44E9-5C17-08DCD803C921
Authorization : Bearer {{AccesToken}}
###

GET {{RestaurantsAPI_HostAddress}}/api/Restaurants/c38388c5-5637-4857-4664-08dcd82c5bc1
Authorization : Bearer {{AccesToken}}
###

GET {{RestaurantsAPI_HostAddress}}/api/Restaurants/d6485b6b-cbf7-455b-3acd-08dcd82b4693
Authorization : Bearer {{AccesToken}}
###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants/create
Authorization : Bearer {{OwnerAccesToken}}
Content-Type: application/json
{
  "Name": "La Croisette",
  "Description": "La Croisette est un restaurant à Chatelaillon-Plage, situé sur le bord de mer, à côté du casino.",
  "Category": "French",
  "HasDelivery": false,
  "ContactEmail": "lacroisette@info.fr",
  "ContactNumber": "05 46 56 78 90",
  "City": "Chatelaillon-Plage",
  "Street" : "Boulevard de la Mer",
  "ZipCode": "17340"
}
###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants/create
Authorization : Bearer {{OwnerAccesToken}}
Content-Type: application/json
{
  "Name": "La Croisette2",
  "Description": "La Croisette est un restaurant à Chatelaillon-Plage, situé sur le bord de mer, à côté du casino.",
  "Category": "French",
  "HasDelivery": false,
  "ContactEmail": "lacroisette@info.fr",
  "ContactNumber": "0546567890",
  "City": "Chatelaillon-Plage",
  "Street" : "Boulevard de la Mer",
  "ZipCode": "17-340"
}
###

GET https://localhost:7226/api/Restaurants/b7c4d6a6-c52a-4a71-1e35-08dcd8322edc
Authorization : Bearer {{AccesToken}}
###

GET https://localhost:7226/api/Restaurants/2a320e91-44ab-4ba0-b5c2-08dcda56a133
Authorization : Bearer {{AccesToken}}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2a320e91-44ab-4ba0-b5c2-08dcda56a133
Authorization : Bearer {{AccesToken}}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{id}
Authorization : Bearer {{AccesToken}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/b7c4d6a6-c52a-4a71-1e35-08dcd8322edc
Authorization : Bearer {{AccesToken}}
Content-Type: application/json
{
 "Name" : "Meat Up",
 "Description" : "Restarant carnivore",
 "HasDelivery" : true
}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/b7c4d6a6-c52a-4a71-1e35-08dcd8322edc
Authorization : Bearer {{AccesToken}}
Content-Type: application/json
{
 "Name" : "MU"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurant/a386205c-79da-4b2b-edf5-08dcdda742c2/dishes/7
Authorization : Bearer {{AccesToken}}
Content-Type: application/json
{
  "name": "Byop",
  "description": "Yo",
  "price": 10,
  "isVegetarian": false,
  "kiloCalories": 120
}
###

POST {{RestaurantsAPI_HostAddress}}/api/Identity/login
Content-Type: application/json
{
  "password": "OwnerP@ssw0rd456!",
  "email": "owner@restaurant.com"
}
###

POST {{RestaurantsAPI_HostAddress}}/api/Identity/register
Content-Type: application/json
{
  "password": "myPassw0rd!",
  "email": "myEmail@example.com"
}

### Créer un Admin
POST {{RestaurantsAPI_HostAddress}}/api/Identity/register
Content-Type: application/json
{
  "password": "AdminP@ssw0rd123!",
  "email": "admin@restaurant.com"
}

### Créer un Owner
POST {{RestaurantsAPI_HostAddress}}/api/Identity/register
Content-Type: application/json
{
  "password": "OwnerP@ssw0rd456!",
  "email": "owner@restaurant.com"
}

### Créer un User lambda
POST {{RestaurantsAPI_HostAddress}}/api/Identity/register
Content-Type: application/json
{
  "password": "UserP@ssw0rd789!",
  "email": "user@example.com"
}