@Host = https://localhost
@Port = 7226


@RestaurantsAPI_HostAddress = {{Host}}:{{Port}}

GET {{RestaurantsAPI_HostAddress}}/api/restaurants

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/8A221E03-F2A4-44E9-5C17-08DCD803C421

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/8A221E03-F2A4-44E9-5C17-08DCD803C921